version: "3.8"
services:
  mysqldb:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: activiti6ui
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql-activiti:/var/lib/mysql
  activiti:
    image: ldavidflorez/activiti-app-mysq:v1
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb
volumes:
  mysql-activiti: